### ISSUE TITLE
Options cannot be Hash when using chef_gem resource

### ISSUE THREAD

**Issue by joraff** [guilhem-cookbooks/gem_specific_install#4]
When using the chef_gem provider, options must be a string and not a hash. action_install method in the SpecificInstall provider needs a hash of options to function properly.

**Comment by jonathanhoskin** [comment]
This is also a problem for me. Will it ever be fixed?

**Comment by scottymarshall** [comment]
I second @jonathanhoskin 's question.

**Comment by guilhem** [comment]
Ok I see what is the problem...
I will try to fix it right now

**Comment by guilhem** [comment]
Can you test this branch: https://github.com/guilhem-cookbooks/gem_specific_install/tree/options_string

**Comment by scottymarshall** [comment]
I seem to have bigger problems now, but it might be simple fix.

My recipe:
```include_recipe "gem_specific_install::_chef"
chef_gem "chef-provisioning-docker" do
  provider Chef::Provider::Package::Rubygems::SpecificInstall
  options "-l https://github.com/scottymarshall/chef-provisioning-docker.git -b socket_issue"
end```

And here the results:
```         * chef_gem[specific_install] action install[2015-02-25T18:42:57+00:00] INFO: Processing chef_gem[specific_install] action install (gem_specific_install::_chef line 23)
       
           - install version 0.2.7 of package specific_install
       Recipe: jmh-docker::docker
         * chef_gem[chef-provisioning-docker] action install[2015-02-25T18:43:00+00:00] INFO: Processing chef_gem[chef-provisioning-docker] action install (jmh-docker::docker line 20)
       
           
           ================================================================================
           Error executing action `install` on resource 'chef_gem[chef-provisioning-docker]'
           ================================================================================
           
           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           Expected process to exit with [0], but received '1'
           ---- Begin output of /opt/chef/embedded/bin/gem specific_install chef-provisioning-docker -l https://github.com/scottymarshall/chef-provisioning-docker.git -b socket_issue ----
           STDOUT: 
           STDERR: Error loading RubyGems plugin "/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/specific_install-0.2.7/lib/rubygems_plugin.rb": cannot load such file -- rubygems/builder (LoadError)
           ERROR:  While executing gem ... (Gem::CommandLineError)
               Unknown command specific_install
           ---- End output of /opt/chef/embedded/bin/gem specific_install chef-provisioning-docker -l https://github.com/scottymarshall/chef-provisioning-docker.git -b socket_issue ----
           Ran /opt/chef/embedded/bin/gem specific_install chef-provisioning-docker -l https://github.com/scottymarshall/chef-provisioning-docker.git -b socket_issue returned 1
           
           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/gem_specific_install/libraries/gem_specific_install.rb:11:in `action_install'
           /tmp/kitchen/cache/cookbooks/jmh-docker/recipes/docker.rb:20:in `from_file'
```

**Comment by obazoud** [comment]
I got same problems here.

**Comment by yozik04** [comment]
Does not work for me as well. Tried both variants. With options as hash and as string.

**Comment by elthariel** [comment]
Still a problem :)
